version: "3.2"

services:
#Mysql Container
  mysql:
    image: mysql:5.7.23
    container_name: mysql
    hostname: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ./mysql.env
    restart: always
    networks:
       - back

#GLPI Container
  glpi:
    image: zenzedoon/glpi_zbs:v02
    container_name : glpi
    hostname: glpi
    ports:
      - "8081:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./glpi/:/var/www/html/glpi
    environment: 
      - TIMEZONE=Afrique/Tunis
    restart: always
    networks:
       - back 
       - front
networks:
   front:
      driver: bridge
   back:

volumes:
   mysql:
   glpi: 
